apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "location-api-producer"
  namespace: "default"
  labels:
    app: "location-api-producer"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "location-api-producer"
  template:
    metadata:
      labels:
        app: "location-api-producer"
    spec:
      containers:
        - name: "location-api-producer"
          image: tarunshrma/udaconnect-location-producer:0.0.6
          imagePullPolicy: IfNotPresent
          env:
          - name: KAFKA_TOPIC
            valueFrom:
              configMapKeyRef:
                name: app-location-map
                key: KAFKA_TOPIC
          - name: KAFKA_SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: app-location-map
                key: KAFKA_SERVER_URL


---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "location-api-producer"
  namespace: "default"
  labels:
    app: "location-api-producer"
spec:
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
      nodePort: 30001
  selector:
    app: "location-api-producer"
  type: "NodePort"
