apiVersion: v1
kind: Service
metadata:
  name: postgres-location
  labels:
    app: postgres-location
spec:
  type: ClusterIP
  selector:
    app: postgres-location
  ports:
   - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-location
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-location
  template:
    metadata:
      labels:
        app: postgres-location
    spec:
      containers:
        - name: postgres-location
          image: postgis/postgis:12-2.5-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: app-location-map
                key: DB_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-location-secret
                key: DB_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: app-location-map
                key: DB_NAME
          volumeMounts:
            - mountPath: /var/lib/locationdb/data
              name: location-db
      volumes:
        - name: location-db
          persistentVolumeClaim:
            claimName: postgres-location-pv-claim