apiVersion: v1
kind: Service
metadata:
  labels:
    app: udaconnect-persons-api
  name: udaconnect-persons-api
spec:
  ports:
  - name: 5000-30002
    port: 5001
    protocol: TCP
    targetPort: 5001
    nodePort: 30002
  selector:
    app: udaconnect-persons-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: udaconnect-persons-api
  name: udaconnect-persons-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udaconnect-persons-api
  template:
    metadata:
      labels:
        app: udaconnect-persons-api
    spec:
      containers:
      - image: tarunshrma/udaconnect-person-app:0.0.2
        name: udaconnect-persons-api
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-location-map
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-location-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-location-map
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-location-map
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-location-map
              key: DB_PORT
      restartPolicy: Always