openapi: 3.0.0
info:
  title: UdaConnect Location API
  version: 1.0.0
servers:
  - url: /api/v1
paths:
  /health:
    get:
      operationId: health
      responses:
        200:
          description: Returns a health check message.
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
  /locations:
    post:
      operationId: addLocation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - person_id
                - creation_time
                - latitude
                - longitude
              properties:
                person_id:
                  type: integer
                creation_time:
                  type: string
                latitude:
                  type: string
                longitude:
                  type: string
      responses:
        201:
          description: Location created.
        400:
          description: Invalid Location data.
