openapi: 3.0.0
info:
  title: UdaConnect Person API
  version: '1.0.0'
servers:
  - url: '/'
paths:
  /v1/persons:
    post:
      tags:
        - udaconnect.person
      description: Creates a new person
      operationId: createPerson
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '400':
          description: Bad request
    get:
      tags:
        - udaconnect.person
      description: Retrieve all persons
      operationId: retrieveAllPersons
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
  /v1/persons/{person_id}:
    get:
      tags:
        - udaconnect.person
      description: Retrieve person by id
      operationId: retrievePerson
      parameters:
        - name: person_id
          in: path
          description: Person id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '404':
          description: Not found
components:
  schemas:
    Person:
      type: object
      properties:
        first_name:
          type: string
          description: First name of the person
        last_name:
          type: string
          description: Last name of the person
        company_name:
          type: string
          description: Company name of the person
      required:
        - first_name
        - last_name
        - company_name
