# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: location-data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13location-data.proto\"]\n\x0cLocationData\x12\x11\n\tperson_id\x18\x01 \x01(\x05\x12\x15\n\rcreation_time\x18\x02 \x01(\t\x12\x10\n\x08latitude\x18\x03 \x01(\t\x12\x11\n\tlongitude\x18\x04 \x01(\t\"\x07\n\x05\x45mpty\"4\n\x10LocationDataList\x12 \n\tlocations\x18\x01 \x03(\x0b\x32\r.LocationData2m\n\x0fLocationService\x12,\n\x0cSaveLocation\x12\r.LocationData\x1a\r.LocationData\x12,\n\x0fGetAllLocations\x12\x06.Empty\x1a\x11.LocationDataListb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'location_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOCATIONDATA._serialized_start=23
  _LOCATIONDATA._serialized_end=116
  _EMPTY._serialized_start=118
  _EMPTY._serialized_end=125
  _LOCATIONDATALIST._serialized_start=127
  _LOCATIONDATALIST._serialized_end=179
  _LOCATIONSERVICE._serialized_start=181
  _LOCATIONSERVICE._serialized_end=290
# @@protoc_insertion_point(module_scope)
